# coding: utf-8

"""
    broker_view_generative_ui

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "broker-view-generative-ui-sdk"
with open('version') as fp:
    VERSION = fp.read().strip()
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 2, < 3",
    "typing-extensions >= 4.7.1, < 5",
]
ASYNC_REQUIRES = [
    "aiohttp >= 3.0.0, < 4",
    "aiohttp-retry >= 2.8.3, < 3",
]
setup(
    name=NAME,
    version=VERSION,
    description="broker_view_generative_ui",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "broker_view_generative_ui"],
    install_requires=REQUIRES,
    extras_require={"async": ASYNC_REQUIRES},    
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    """,  # noqa: E501
    package_data={"broker_view_generative_ui_sdk": ["py.typed"]},
)
